package br.uninove.desktop.view;

import br.uninove.desktop.model.Funcionario;
import br.uninove.desktop.model.Endereco;
import br.uninove.desktop.repository.FuncionarioDAO;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
/**
 *
 * @author Bruno
 */
public class CadastrarFuncionario extends javax.swing.JFrame {
    Funcionario func;
    FuncionarioDAO funcDao = new FuncionarioDAO();
    /**
     * Creates new form CadastrarFuncionario1
     */
    public CadastrarFuncionario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtDtNascFnc = new javax.swing.JTextField();
        txtEmailFunc = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnCadFunc = new javax.swing.JButton();
        btnLimpCadFun = new javax.swing.JButton();
        btnConsulFunc = new javax.swing.JButton();
        txtNomeFunc = new javax.swing.JTextField();
        txtDtAdmissao = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        txtEstFunc = new javax.swing.JTextField();
        txtCidFunc = new javax.swing.JTextField();
        txtRuaFunc = new javax.swing.JTextField();
        txtCepFunc = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtBairroFunc = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtNumFunc = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtCpfFunc = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtSalarioFunc = new javax.swing.JTextField();
        txtCodFunc = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtTelFunc = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtInseriIDFunc = new javax.swing.JTextField();
        btnAltFuncID = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        btnMostrarFunc = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("WV DATABASE | CADASTRAR E ALTERAR FUNCIONARIO | Versão 1.0.0 | 2018");
        setLocation(new java.awt.Point(265, 150));
        setResizable(false);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Data de Admissão:");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/logo_WVTrata3.png"))); // NOI18N
        jLabel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Email:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Data de Nascimento:");

        btnCadFunc.setBackground(new java.awt.Color(0, 102, 102));
        btnCadFunc.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCadFunc.setForeground(new java.awt.Color(204, 204, 204));
        btnCadFunc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cadMod1.png"))); // NOI18N
        btnCadFunc.setText("Cadastrar");
        btnCadFunc.setToolTipText("INSIRA OS DADOS DO FUNCIONÁRIO NOS CAMPOS AO LADO E CLIQUE NO BOTÃO!");
        btnCadFunc.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnCadFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadFuncActionPerformed(evt);
            }
        });

        btnLimpCadFun.setBackground(new java.awt.Color(204, 204, 0));
        btnLimpCadFun.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnLimpCadFun.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/limpar2Mod.png"))); // NOI18N
        btnLimpCadFun.setText("Limpar");
        btnLimpCadFun.setToolTipText("CLIQUE AQUI PARA LIMPAR OS DADOS PREENCHIDOS!");
        btnLimpCadFun.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnLimpCadFun.setMaximumSize(new java.awt.Dimension(101, 25));
        btnLimpCadFun.setMinimumSize(new java.awt.Dimension(101, 25));
        btnLimpCadFun.setPreferredSize(new java.awt.Dimension(101, 25));
        btnLimpCadFun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpCadFunActionPerformed(evt);
            }
        });

        btnConsulFunc.setBackground(new java.awt.Color(0, 102, 102));
        btnConsulFunc.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnConsulFunc.setForeground(new java.awt.Color(204, 204, 204));
        btnConsulFunc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/lupaPhoto2.png"))); // NOI18N
        btnConsulFunc.setText("Consultar");
        btnConsulFunc.setToolTipText("CLIQUE AQUI PARA ABRIR A TELA DE CONSULTA!");
        btnConsulFunc.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnConsulFunc.setMaximumSize(new java.awt.Dimension(101, 25));
        btnConsulFunc.setMinimumSize(new java.awt.Dimension(101, 25));
        btnConsulFunc.setPreferredSize(new java.awt.Dimension(101, 25));
        btnConsulFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsulFuncActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Nome:");

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Rua:");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Número:");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Bairro:");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("Estado:");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText("Cidade:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("CEP:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtBairroFunc)
                            .addComponent(txtRuaFunc, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEstFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCepFunc, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNumFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel15)
                        .addGap(10, 10, 10)
                        .addComponent(txtCidFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtRuaFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(txtNumFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtBairroFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(txtCidFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtEstFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txtCepFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jLabel10.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel10.setText("Endereço:");

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText("CPF:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Salário:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Código Funcionário:");

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setText("Telefone:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Insira o ID:");

        btnAltFuncID.setBackground(new java.awt.Color(0, 153, 153));
        btnAltFuncID.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAltFuncID.setForeground(new java.awt.Color(102, 102, 102));
        btnAltFuncID.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/alterar2Mod.png"))); // NOI18N
        btnAltFuncID.setText("Alterar");
        btnAltFuncID.setToolTipText("INSIRA O ID DO FUNCIONÁRIO NO CAMPO AO LADO, PREENCHA OS CAMPOS COM OS DADOS NOVOS E CLIQUE NO BOTÃO!");
        btnAltFuncID.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnAltFuncID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAltFuncIDActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(204, 0, 0));
        jLabel18.setText("OBS: Insira o ID somente para ALTERAÇÃO!!");

        btnMostrarFunc.setBackground(new java.awt.Color(0, 153, 153));
        btnMostrarFunc.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnMostrarFunc.setForeground(new java.awt.Color(102, 102, 102));
        btnMostrarFunc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/mostrar2Mod.png"))); // NOI18N
        btnMostrarFunc.setText("Mostrar");
        btnMostrarFunc.setToolTipText("INSIRA O ID DO FUNCIONÁRIO NO CAMPO AO LADO E CLIQUE NO BOTÃO PARA MOSTRAR OS DADOS NOS CAMPOS AO LADO!");
        btnMostrarFunc.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnMostrarFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarFuncActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel16)
                                    .addGap(2, 2, 2)
                                    .addComponent(txtCpfFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel8)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtEmailFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel9)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtDtNascFnc, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtDtAdmissao, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtNomeFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtSalarioFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtCodFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTelFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtInseriIDFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addGap(37, 37, 37)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnMostrarFunc, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                                    .addComponent(btnAltFuncID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jLabel18)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(btnCadFunc)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnConsulFunc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnLimpCadFun, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(79, 79, 79))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNomeFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtDtNascFnc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDtAdmissao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(txtCpfFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(txtEmailFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtSalarioFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(txtCodFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(txtTelFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnConsulFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCadFunc))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLimpCadFun, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnMostrarFunc, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAltFuncID)
                            .addComponent(txtInseriIDFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel18))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadFuncActionPerformed
        DecimalFormat deci = new DecimalFormat("0.00");
        //Atribuindo os valores em uma variavel
        String nome = txtNomeFunc.getText();
        String tel = txtTelFunc.getText();
        String email = txtEmailFunc.getText();
        String cpf = txtCpfFunc.getText();
        String dTNasc = txtDtNascFnc.getText();
        String codFunc = txtCodFunc.getText();
        String dTAdm = txtDtAdmissao.getText();
        float salario = Float.parseFloat(txtSalarioFunc.getText());
        
        //Criando um objeto do tipo Endereco para setar os valores
        Endereco end = new Endereco();
        
        //Passando valores atraves do construtor com 8 parametros
        func = new Funcionario(nome, tel, email, cpf, dTNasc, codFunc, dTAdm, salario);
        
        //Setando os valores para a classe Endereco
        end.setRua(txtRuaFunc.getText());
        end.setNumero(Integer.parseInt(txtNumFunc.getText()));
        end.setBairro(txtBairroFunc.getText());
        end.setCidade(txtCidFunc.getText());
        end.setEstado(txtEstFunc.getText());
        end.setCep(Integer.parseInt(txtCepFunc.getText()));
        
        func.setEndereco(end);
        
        funcDao.inserirFuncionario(func);
        
        /*
        //mostrando os valores no painel JOptionPane
         JOptionPane.showMessageDialog(null, 
            "DADOS DO FUNCIONÁRIO CADASTRADO\n"+
            "\t - Nome: "+func.getNome()+
            "\n\t - Data de nascimento: "+func.getData_nasc()+
            "\n\t - Data de Admissão: "+func.getData_admissao()+
            "\n\t - CPF: "+func.getCpf()+
            "\n\t - Email: "+func.getEmail()+
            "\n\t - Salário: R$ "+deci.format(func.getSalario())+
            "\n\t - Código do funcionário: "+func.getCodFunc()+   
            "\n\t - Telefone: "+func.getTelefone()+
                 
            "\n\nENDEREÇO\n"+
            "\t - Rua: "+end.getRua()+" \t\t\t  - Numero: "+end.getNumero()+
            "\n\t - Bairro: "+end.getBairro()+" \t\t\t  - Cidade: "+end.getCidade()+
            "\n\t - Estado: "+end.getEstado()+" \t\t\t  - Cep: "+ end.getCep());*/
        
    }//GEN-LAST:event_btnCadFuncActionPerformed

    private void btnLimpCadFunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpCadFunActionPerformed
        //Limpar todos os dados
        int limpTela = JOptionPane.showConfirmDialog(this, "Você quer mesmo limpar a tela?","LIMPAR TELA",
                                                     JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        
        if(limpTela == 0){
            txtBairroFunc.setText(null);
            txtCepFunc.setText(null);
            txtCidFunc.setText(null);
            txtCodFunc.setText(null);
            txtCpfFunc.setText(null);
            txtDtAdmissao.setText(null);
            txtDtNascFnc.setText(null);
            txtEmailFunc.setText(null);
            txtEstFunc.setText(null);
            txtNomeFunc.setText(null);
            txtNumFunc.setText(null);
            txtRuaFunc.setText(null);
            txtSalarioFunc.setText(null);
            txtTelFunc.setText(null);
           
            txtNomeFunc.grabFocus();
        }
    }//GEN-LAST:event_btnLimpCadFunActionPerformed

    private void btnConsulFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsulFuncActionPerformed
        ConsultarFuncionario altFunc = new ConsultarFuncionario();
        
        altFunc.setVisible(true);
    }//GEN-LAST:event_btnConsulFuncActionPerformed

    private void btnMostrarFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarFuncActionPerformed
        List<Funcionario> listaFunc = new ArrayList<Funcionario>();
        
        int funcID = Integer.parseInt(txtInseriIDFunc.getText());
        
        listaFunc = funcDao.listarFuncID(funcID);
        
        for(int indice = 0; indice < listaFunc.size(); indice++){
            Funcionario funcio = (Funcionario) listaFunc.get(indice);
        
                       txtNomeFunc.setText(funcio.getNome());
                       txtDtNascFnc.setText(funcio.getData_nasc());
                       txtDtAdmissao.setText(funcio.getData_admissao());
                       txtCpfFunc.setText(funcio.getCpf());
                       txtEmailFunc.setText(funcio.getEmail());
                       txtSalarioFunc.setText(Float.toString(funcio.getSalario()));
                       txtCodFunc.setText(funcio.getCodFunc());
                       txtTelFunc.setText(funcio.getTelefone());
                       txtRuaFunc.setText(funcio.getEndereco().getRua());
                       txtNumFunc.setText(Integer.toString(funcio.getEndereco().getNumero()));
                       txtBairroFunc.setText(funcio.getEndereco().getBairro());
                       txtCidFunc.setText(funcio.getEndereco().getCidade());
                       txtEstFunc.setText(funcio.getEndereco().getEstado());
                       txtCepFunc.setText(Integer.toString(funcio.getEndereco().getCep()));
        }

    }//GEN-LAST:event_btnMostrarFuncActionPerformed

    private void btnAltFuncIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAltFuncIDActionPerformed
        String nome = txtNomeFunc.getText();
        String tel = txtTelFunc.getText();
        String email = txtEmailFunc.getText();
        String cpf = txtCpfFunc.getText();
        String dTNasc = txtDtNascFnc.getText();
        String codFunc = txtCodFunc.getText();
        String dTAdm = txtDtAdmissao.getText();
        float salario = Float.parseFloat(txtSalarioFunc.getText());
        
        //Criando um objeto do tipo Endereco para setar os valores
        Endereco end = new Endereco();
        
        //Passando valores atraves do construtor com 8 parametros
        func = new Funcionario(nome, tel, email, cpf, dTNasc, codFunc, dTAdm, salario);
        
        //Setando os valores para a classe Endereco
        end.setRua(txtRuaFunc.getText());
        end.setNumero(Integer.parseInt(txtNumFunc.getText()));
        end.setBairro(txtBairroFunc.getText());
        end.setCidade(txtCidFunc.getText());
        end.setEstado(txtEstFunc.getText());
        end.setCep(Integer.parseInt(txtCepFunc.getText()));
        
        func.setEndereco(end);
        
        //atribuindo o valor do id a uma variavel
        int idFunc = Integer.parseInt(txtInseriIDFunc.getText());
        
        //setando o id do funcionario
        func.setId(idFunc);
        
        funcDao.alterarFuncionario(func);
    }//GEN-LAST:event_btnAltFuncIDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastrarFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastrarFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastrarFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastrarFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastrarFuncionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAltFuncID;
    private javax.swing.JButton btnCadFunc;
    private javax.swing.JButton btnConsulFunc;
    private javax.swing.JButton btnLimpCadFun;
    private javax.swing.JButton btnMostrarFunc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtBairroFunc;
    private javax.swing.JTextField txtCepFunc;
    private javax.swing.JTextField txtCidFunc;
    private javax.swing.JTextField txtCodFunc;
    private javax.swing.JTextField txtCpfFunc;
    private javax.swing.JTextField txtDtAdmissao;
    private javax.swing.JTextField txtDtNascFnc;
    private javax.swing.JTextField txtEmailFunc;
    private javax.swing.JTextField txtEstFunc;
    private javax.swing.JTextField txtInseriIDFunc;
    private javax.swing.JTextField txtNomeFunc;
    private javax.swing.JTextField txtNumFunc;
    private javax.swing.JTextField txtRuaFunc;
    private javax.swing.JTextField txtSalarioFunc;
    private javax.swing.JTextField txtTelFunc;
    // End of variables declaration//GEN-END:variables
}
