/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.uninove.desktop.view;

import br.uninove.desktop.model.Cliente;
import br.uninove.desktop.repository.ClienteDAO;
import java.util.ArrayList;
import java.util.List;
import javax.swing.*;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Bruno
 */
public class ConsultarCliente extends javax.swing.JFrame {

    /**
     * Creates new form AlterarCliente
     */
    public ConsultarCliente() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnExcluirTodosClie = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnConsultTodos = new javax.swing.JButton();
        btnConsultCliNome = new javax.swing.JButton();
        txtConsuCliNome = new javax.swing.JTextField();
        btnExcluiCli = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtExCli = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("WV DATABASE | CONSULTAR CLIENTE | Versão 1.0.0 | 2018");
        setLocation(new java.awt.Point(208, 145));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        btnExcluirTodosClie.setBackground(new java.awt.Color(153, 0, 0));
        btnExcluirTodosClie.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnExcluirTodosClie.setForeground(new java.awt.Color(204, 204, 204));
        btnExcluirTodosClie.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/excluirPessoaMod2.png"))); // NOI18N
        btnExcluirTodosClie.setText("Excluir Todos");
        btnExcluirTodosClie.setToolTipText("CLIQUE NO BOTÃO PARA EXCLUIR TODOS OS CLIENTES!");
        btnExcluirTodosClie.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnExcluirTodosClie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirTodosClieActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NOME", "DATA DE NASCIMENTO", "TELEFONE", "CPF", "EMAIL", "RUA", "NÚMERO", "BAIRRO", "CIDADE", "ESTADO", "CEP"
            }
        ));
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTable1.setColumnSelectionAllowed(true);
        jTable1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setViewportView(jTable1);
        jTable1.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 898, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 361, Short.MAX_VALUE)
        );

        btnConsultTodos.setBackground(new java.awt.Color(0, 102, 102));
        btnConsultTodos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnConsultTodos.setForeground(new java.awt.Color(204, 204, 204));
        btnConsultTodos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/lupaPhoto2.png"))); // NOI18N
        btnConsultTodos.setText("Consultar todos");
        btnConsultTodos.setToolTipText("CLIQUE NO BOTÃO PARA CONSULTAR TODOS OS CLIENTES!");
        btnConsultTodos.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnConsultTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultTodosActionPerformed(evt);
            }
        });

        btnConsultCliNome.setBackground(new java.awt.Color(0, 102, 102));
        btnConsultCliNome.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnConsultCliNome.setForeground(new java.awt.Color(204, 204, 204));
        btnConsultCliNome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/lupaPhoto2.png"))); // NOI18N
        btnConsultCliNome.setText("Consultar Cliente");
        btnConsultCliNome.setToolTipText("INSIRA O NOME NO CAMPO ABAIXO E CLIQUE NO BOTÃO!");
        btnConsultCliNome.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnConsultCliNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultCliNomeActionPerformed(evt);
            }
        });

        txtConsuCliNome.setToolTipText("");
        txtConsuCliNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtConsuCliNomeActionPerformed(evt);
            }
        });

        btnExcluiCli.setBackground(new java.awt.Color(153, 0, 0));
        btnExcluiCli.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnExcluiCli.setForeground(new java.awt.Color(204, 204, 204));
        btnExcluiCli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/excluirPessoaMod2.png"))); // NOI18N
        btnExcluiCli.setText("Excluir Cliente");
        btnExcluiCli.setToolTipText("INSIRA O ID DO CLIENTE E CLIQUE NO BOTÃO!");
        btnExcluiCli.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnExcluiCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluiCliActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Insira o nome:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Insira o ID:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtConsuCliNome, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnConsultCliNome, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(txtExCli, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnExcluiCli)
                                .addGap(36, 36, 36)
                                .addComponent(btnConsultTodos)
                                .addGap(34, 34, 34)
                                .addComponent(btnExcluirTodosClie)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnConsultCliNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnConsultTodos, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnExcluirTodosClie)
                        .addComponent(btnExcluiCli)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtConsuCliNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtExCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //metodo com os nomes das coluna
    private void colunaTabela(DefaultTableModel tabelaModel){
        
        tabelaModel.addColumn("ID");
        tabelaModel.addColumn("NOME"); 
        tabelaModel.addColumn("DATA DE NASCIMENTO");
        tabelaModel.addColumn("TELEFONE");
        tabelaModel.addColumn("CPF");
        tabelaModel.addColumn("EMAIL");
        tabelaModel.addColumn("RUA");
        tabelaModel.addColumn("NUMERO");
        tabelaModel.addColumn("BAIRRO");
        tabelaModel.addColumn("CIDADE");
        tabelaModel.addColumn("ESTADO");
        tabelaModel.addColumn("CEP");
        
        
    }

    private void btnConsultTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultTodosActionPerformed
         ClienteDAO cDao = new ClienteDAO();
        
        List<Cliente> listaTodosClientes = new ArrayList<Cliente>();
        
        listaTodosClientes = cDao.listarCliente();
       
        DefaultTableModel tabelaModel = new DefaultTableModel();
        
        //trazendo os nomes das colunas da tabela atraves do metodo
        colunaTabela(tabelaModel);
        
        for (Cliente clientelocal : listaTodosClientes){
            tabelaModel.addRow(new Object[]{
            
            clientelocal.getId(),
            clientelocal.getNome(),
            clientelocal.getData_nasc(),
            clientelocal.getTelefone(),
            clientelocal.getCpf(),
            clientelocal.getEmail(),
            clientelocal.getEndereco().getRua(),
            clientelocal.getEndereco().getNumero(),
            clientelocal.getEndereco().getBairro(),
            clientelocal.getEndereco().getCidade(),
            clientelocal.getEndereco().getEstado(),
            clientelocal.getEndereco().getCep()
                    });
        
        }
        
        jTable1.setModel(tabelaModel);
        jTable1.getColumnModel().getColumn(0).setPreferredWidth(50);
        jTable1.getColumnModel().getColumn(1).setPreferredWidth(150);
        jTable1.getColumnModel().getColumn(2).setPreferredWidth(150);
        jTable1.getColumnModel().getColumn(3).setPreferredWidth(100);
        jTable1.getColumnModel().getColumn(4).setPreferredWidth(100);
        jTable1.getColumnModel().getColumn(5).setPreferredWidth(150);
        jTable1.getColumnModel().getColumn(6).setPreferredWidth(100);
        jTable1.getColumnModel().getColumn(7).setPreferredWidth(80);
        jTable1.getColumnModel().getColumn(8).setPreferredWidth(80);
        jTable1.getColumnModel().getColumn(9).setPreferredWidth(80);
        jTable1.getColumnModel().getColumn(10).setPreferredWidth(80);
        jTable1.getColumnModel().getColumn(11).setPreferredWidth(80);
        
        
        /*DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
        jTable1.setRowSorter(new TableRowSorter(modelo));*/
    }//GEN-LAST:event_btnConsultTodosActionPerformed
//metodo do botao de consultar todos
    public JButton getBtnConsultTodos() {
        return btnConsultTodos;
    }

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        
    }//GEN-LAST:event_formWindowOpened

    
    private void btnConsultCliNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultCliNomeActionPerformed
        ClienteDAO cDao = new ClienteDAO();
        //pegando o nome da caixa de texto e atribuindo em uma variavel
        String nome = txtConsuCliNome.getText();
        
        List<Cliente> listCliNome = new ArrayList<Cliente>();
        listCliNome = cDao.listarClienteNome(nome);
        
        DefaultTableModel tabelaModel = new DefaultTableModel();
        
        //trazendo os nomes das colunas da tabela atraves do metodo
        colunaTabela(tabelaModel);
        
        for (Cliente clientelocal : listCliNome){
            tabelaModel.addRow(new Object[]{
            
            clientelocal.getId(),
            clientelocal.getNome(),
            clientelocal.getData_nasc(),
            clientelocal.getTelefone(),
            clientelocal.getCpf(),
            clientelocal.getEmail(),
            clientelocal.getEndereco().getRua(),
            clientelocal.getEndereco().getNumero(),
            clientelocal.getEndereco().getBairro(),
            clientelocal.getEndereco().getCidade(),
            clientelocal.getEndereco().getEstado(),
            clientelocal.getEndereco().getCep()
                    });
        }
        jTable1.setModel(tabelaModel);
        jTable1.getColumnModel().getColumn(0).setPreferredWidth(50);
        jTable1.getColumnModel().getColumn(1).setPreferredWidth(150);
        jTable1.getColumnModel().getColumn(2).setPreferredWidth(150);
        jTable1.getColumnModel().getColumn(3).setPreferredWidth(100);
        jTable1.getColumnModel().getColumn(4).setPreferredWidth(100);
        jTable1.getColumnModel().getColumn(5).setPreferredWidth(150);
        jTable1.getColumnModel().getColumn(6).setPreferredWidth(100);
        jTable1.getColumnModel().getColumn(7).setPreferredWidth(80);
        jTable1.getColumnModel().getColumn(8).setPreferredWidth(80);
        jTable1.getColumnModel().getColumn(9).setPreferredWidth(80);
        jTable1.getColumnModel().getColumn(10).setPreferredWidth(80);
        jTable1.getColumnModel().getColumn(11).setPreferredWidth(80);
    }//GEN-LAST:event_btnConsultCliNomeActionPerformed

    private void btnExcluiCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluiCliActionPerformed
        ClienteDAO cDao = new ClienteDAO();
        int id = Integer.parseInt(txtExCli.getText());
        
        cDao.excluirCliID(id);
        
        cDao.listarCliente();
        btnConsultTodosActionPerformed(evt);
        
        
    }//GEN-LAST:event_btnExcluiCliActionPerformed

    private void btnExcluirTodosClieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirTodosClieActionPerformed
        ClienteDAO cDao = new ClienteDAO();
      int excluiTodos = JOptionPane.showConfirmDialog(this, "Você quer mesmo excluir todos os clientes cadastrados?","Limpa Tela",
                JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(excluiTodos == 0){
            cDao.excluirTodosCli();
        }
    }//GEN-LAST:event_btnExcluirTodosClieActionPerformed

    private void txtConsuCliNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtConsuCliNomeActionPerformed
       // TODO add your handling code here:
    }//GEN-LAST:event_txtConsuCliNomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultarCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsultCliNome;
    private javax.swing.JButton btnConsultTodos;
    private javax.swing.JButton btnExcluiCli;
    private javax.swing.JButton btnExcluirTodosClie;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtConsuCliNome;
    private javax.swing.JTextField txtExCli;
    // End of variables declaration//GEN-END:variables
}
