/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.uninove.desktop.view;

import br.uninove.desktop.model.Funcionario;
import br.uninove.desktop.repository.FuncionarioDAO;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Bruno
 */
public class ConsultarFuncionario extends javax.swing.JFrame {
    FuncionarioDAO funcDao = new FuncionarioDAO();

    /**
     * Creates new form AlterarFuncionario
     */
    public ConsultarFuncionario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSelecionar = new javax.swing.JButton();
        btnExcluiFunc = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnselecionarUm = new javax.swing.JButton();
        txtInserirNome = new javax.swing.JTextField();
        btnExcUmFunc = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtInserirID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("WV DATABASE | CONSULTAR FUNCIONÁRIO | Versão 1.0.0 | 2018");
        setLocation(new java.awt.Point(208, 145));
        setResizable(false);

        btnSelecionar.setBackground(new java.awt.Color(0, 102, 102));
        btnSelecionar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSelecionar.setForeground(new java.awt.Color(204, 204, 204));
        btnSelecionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/lupaPhoto2.png"))); // NOI18N
        btnSelecionar.setText("Consultar todos");
        btnSelecionar.setToolTipText("CLIQUE NO BOTÃO PARA CONSULTAR TODOS OS FUNCIONÁRIOS!");
        btnSelecionar.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnSelecionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelecionarActionPerformed(evt);
            }
        });

        btnExcluiFunc.setBackground(new java.awt.Color(153, 0, 0));
        btnExcluiFunc.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnExcluiFunc.setForeground(new java.awt.Color(204, 204, 204));
        btnExcluiFunc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/excluirPessoaMod1.png"))); // NOI18N
        btnExcluiFunc.setText("Excluir todos");
        btnExcluiFunc.setToolTipText("CLIQUE NO BOTÃO PARA EXCLUIR TODOS OS FUNCIONÁRIOS!");
        btnExcluiFunc.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnExcluiFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluiFuncActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NOME", "DATA DE NASCIMENTO", "DATA DE ADMISSÃO", "CPF", "EMAIL", "SALÁRIO", "CÓDIGO DO FUNCIONÁRIO", "TELEFONE", "RUA", "NÚMERO", "BAIRRO", "CIDADE", "ESTADO", "CEP"
            }
        ));
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 898, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 354, Short.MAX_VALUE)
        );

        btnselecionarUm.setBackground(new java.awt.Color(0, 102, 102));
        btnselecionarUm.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnselecionarUm.setForeground(new java.awt.Color(204, 204, 204));
        btnselecionarUm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/lupaPhoto2.png"))); // NOI18N
        btnselecionarUm.setText("Consultar Funcionário");
        btnselecionarUm.setToolTipText("INSIRA O NOME NO CAMPO ABAIXO E CLIQUE NO BOTÃO!");
        btnselecionarUm.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnselecionarUm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnselecionarUmActionPerformed(evt);
            }
        });

        btnExcUmFunc.setBackground(new java.awt.Color(153, 0, 0));
        btnExcUmFunc.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnExcUmFunc.setForeground(new java.awt.Color(204, 204, 204));
        btnExcUmFunc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/excluirPessoaMod1.png"))); // NOI18N
        btnExcUmFunc.setText("Excluir Funcionário");
        btnExcUmFunc.setToolTipText("INSIRA O ID DO FUNCIONÁRIO E CLIQUE NO BOTÃO!");
        btnExcUmFunc.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnExcUmFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcUmFuncActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Insira o Nome:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Insira o ID:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnselecionarUm)
                            .addComponent(txtInserirNome, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(txtInserirID, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnExcUmFunc)
                                .addGap(31, 31, 31)
                                .addComponent(btnSelecionar)
                                .addGap(32, 32, 32)
                                .addComponent(btnExcluiFunc)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnExcluiFunc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnExcUmFunc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSelecionar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnselecionarUm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtInserirNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtInserirID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSelecionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelecionarActionPerformed
                   DecimalFormat deci = new DecimalFormat("0.00");
                   //classe para colocar minha lista na tabela
                   DefaultTableModel tablemodel = new DefaultTableModel();
                   
                   //trazendo o metodo da listagem
                   funcDao.listaFuncionario();
                   List<Funcionario> listaFuncionario = new ArrayList<>();
                   
                   //atribuindo para a minha lista local os conteudos 
                   listaFuncionario = funcDao.listaFuncionario();
                   
                   tablemodel.addColumn("ID");
                   tablemodel.addColumn("NOME"); 
                   tablemodel.addColumn("DATA DE NASCIMENTO");
                   tablemodel.addColumn("DATA DE ADMISSÃO");
                   tablemodel.addColumn("CPF");
                   tablemodel.addColumn("EMAIL");
                   tablemodel.addColumn("SALÁRIO");
                   tablemodel.addColumn("CÓDIGO DO FUNCIONÁRIO");
                   tablemodel.addColumn("TELEFONE");
                   tablemodel.addColumn("RUA");
                   tablemodel.addColumn("NUMERO");
                   tablemodel.addColumn("BAIRRO");
                   tablemodel.addColumn("CIDADE");
                   tablemodel.addColumn("ESTADO");
                   tablemodel.addColumn("CEP");
                   
                   for(Funcionario funcLocal : listaFuncionario){
                       tablemodel.addRow(new Object[]{
                       funcLocal.getId(),
                       funcLocal.getNome(),
                       funcLocal.getData_nasc(),
                       funcLocal.getData_admissao(),
                       funcLocal.getCpf(),
                       funcLocal.getEmail(),
                       "R$ "+deci.format(funcLocal.getSalario()),
                       funcLocal.getCodFunc(),
                       funcLocal.getTelefone(),
                       funcLocal.getEndereco().getRua(),
                       funcLocal.getEndereco().getNumero(),
                       funcLocal.getEndereco().getBairro(),
                       funcLocal.getEndereco().getCidade(),
                       funcLocal.getEndereco().getEstado(),
                       funcLocal.getEndereco().getCep()
                               
                       });
                       jTable1.setModel(tablemodel);
                       jTable1.getColumnModel().getColumn(0).setPreferredWidth(50);
                       jTable1.getColumnModel().getColumn(1).setPreferredWidth(150);
                       jTable1.getColumnModel().getColumn(2).setPreferredWidth(150);
                       jTable1.getColumnModel().getColumn(3).setPreferredWidth(100);
                       jTable1.getColumnModel().getColumn(4).setPreferredWidth(100);
                       jTable1.getColumnModel().getColumn(5).setPreferredWidth(150);
                       jTable1.getColumnModel().getColumn(6).setPreferredWidth(100);
                       jTable1.getColumnModel().getColumn(7).setPreferredWidth(100);
                       jTable1.getColumnModel().getColumn(8).setPreferredWidth(100);
                       jTable1.getColumnModel().getColumn(9).setPreferredWidth(100);
                       jTable1.getColumnModel().getColumn(10).setPreferredWidth(80);
                       jTable1.getColumnModel().getColumn(11).setPreferredWidth(80);
                       jTable1.getColumnModel().getColumn(12).setPreferredWidth(80);
                       jTable1.getColumnModel().getColumn(13).setPreferredWidth(80);
                       jTable1.getColumnModel().getColumn(14).setPreferredWidth(80);
                   }
                   
                   
    }//GEN-LAST:event_btnSelecionarActionPerformed

    private void btnselecionarUmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnselecionarUmActionPerformed
                   DecimalFormat deci = new DecimalFormat("0.00");
                   //atribuindo a variavel nome o valor colocado na caixa de texto
                   String nome = txtInserirNome.getText();
                   
                   List<Funcionario> listaFuncionario = new ArrayList<Funcionario>();
                   
                   listaFuncionario = funcDao.listarFuncNome(nome);
                   
                   DefaultTableModel tablemodel = new DefaultTableModel();
                   
                   tablemodel.addColumn("ID");
                   tablemodel.addColumn("NOME"); 
                   tablemodel.addColumn("DATA DE NASCIMENTO");
                   tablemodel.addColumn("DATA DE ADMISSÃO");
                   tablemodel.addColumn("CPF");
                   tablemodel.addColumn("EMAIL");
                   tablemodel.addColumn("SALÁRIO");
                   tablemodel.addColumn("CÓDIGO DO FUNCIONÁRIO");
                   tablemodel.addColumn("TELEFONE");
                   tablemodel.addColumn("RUA");
                   tablemodel.addColumn("NUMERO");
                   tablemodel.addColumn("BAIRRO");
                   tablemodel.addColumn("CIDADE");
                   tablemodel.addColumn("ESTADO");
                   tablemodel.addColumn("CEP");
                   
                   for(Funcionario funcLocal : listaFuncionario){
                       tablemodel.addRow(new Object[]{
                       
                       funcLocal.getId(),
                       funcLocal.getNome(),
                       funcLocal.getData_nasc(),
                       funcLocal.getData_admissao(),
                       funcLocal.getCpf(),
                       funcLocal.getEmail(),
                       "R$ "+deci.format(funcLocal.getSalario()),
                       funcLocal.getCodFunc(),
                       funcLocal.getTelefone(),
                       funcLocal.getEndereco().getRua(),
                       funcLocal.getEndereco().getNumero(),
                       funcLocal.getEndereco().getBairro(),
                       funcLocal.getEndereco().getCidade(),
                       funcLocal.getEndereco().getEstado(),
                       funcLocal.getEndereco().getCep()
                       
                       });
                   jTable1.setModel(tablemodel);
                   jTable1.getColumnModel().getColumn(0).setPreferredWidth(50);
                       jTable1.getColumnModel().getColumn(1).setPreferredWidth(150);
                       jTable1.getColumnModel().getColumn(2).setPreferredWidth(150);
                       jTable1.getColumnModel().getColumn(3).setPreferredWidth(100);
                       jTable1.getColumnModel().getColumn(4).setPreferredWidth(100);
                       jTable1.getColumnModel().getColumn(5).setPreferredWidth(150);
                       jTable1.getColumnModel().getColumn(6).setPreferredWidth(100);
                       jTable1.getColumnModel().getColumn(7).setPreferredWidth(100);
                       jTable1.getColumnModel().getColumn(8).setPreferredWidth(100);
                       jTable1.getColumnModel().getColumn(9).setPreferredWidth(100);
                       jTable1.getColumnModel().getColumn(10).setPreferredWidth(80);
                       jTable1.getColumnModel().getColumn(11).setPreferredWidth(80);
                       jTable1.getColumnModel().getColumn(12).setPreferredWidth(80);
                       jTable1.getColumnModel().getColumn(13).setPreferredWidth(80);
                       jTable1.getColumnModel().getColumn(14).setPreferredWidth(80);
                   }
                           
                   
    }//GEN-LAST:event_btnselecionarUmActionPerformed

    private void btnExcUmFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcUmFuncActionPerformed
      int id = Integer.parseInt(txtInserirID.getText());
        
      funcDao.excluirFuncID(id);
      
      funcDao.listaFuncionario();
      
        btnSelecionarActionPerformed(evt);
        
    }//GEN-LAST:event_btnExcUmFuncActionPerformed

    private void btnExcluiFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluiFuncActionPerformed
       int excluiFunc = JOptionPane.showConfirmDialog(this, "Você quer mesmo excluir todos os funcionários?","Limpa Tela",
               JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
       if(excluiFunc == 0){
        funcDao.excluirTodosFunc();
       }
    }//GEN-LAST:event_btnExcluiFuncActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultarFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultarFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultarFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultarFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultarFuncionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExcUmFunc;
    private javax.swing.JButton btnExcluiFunc;
    private javax.swing.JButton btnSelecionar;
    private javax.swing.JButton btnselecionarUm;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtInserirID;
    private javax.swing.JTextField txtInserirNome;
    // End of variables declaration//GEN-END:variables
}
